### ISSUE TITLE
Training entity error

### ISSUE THREAD

**Issue by Vishnubala95** [quyingqi/kbqa-ar-smcnn#2]
![screenshot from 2018-05-05 18-03-20](https://user-images.githubusercontent.com/36667048/39663318-b55d69d8-508e-11e8-8a0c-e044deb7ebe9.png)

Hi,
In this screenshot the command (sh  process.py) is not clear to me since i found only process.sh in the git file extraction. Kindly clear my doubt and update it asap.

**Comment by quyingqi** [comment]
Yes, it's a mistake. I have fixed it. Thanks for your feedback.
